In [3]:
#1. Convert List to 1D Array
import numpy as np

list1 = [12.23, 13.32, 100, 36.32]
print("Original List:", list1)

arr_val = np.array(list1)
print("One-dimensional NumPy array:", arr_val)

Original List: [12.23, 13.32, 100, 36.32]
One-dimensional NumPy array: [ 12.23  13.32 100.    36.32]


In [4]:
#2. Create 3x3 Matrix (2?10). Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.
import numpy as np

arr_val = np.arange(2,11).reshape(3,3)

print(arr_val)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [6]:
#3. Null Vector (10) & Update Sixth Value. Write a NumPy program to create a null vector of size 10 and update the sixth value to 11.
import numpy as np

null_vector = np.zeros(10)
print(null_vector)

null_vector[6] = 11
print("Update sixth value to 11", null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11 [ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [7]:
#4. Array from 12 to 38. Write a NumPy program to create an array with values ranging from 12 to 38.
import numpy as np

arr_val = np.arange(12, 38)

print(arr_val)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [8]:
#5. Convert Array to Float Type. Write a NumPy program to convert an array to a floating type.
import numpy as np

org_val = np.array([1, 2, 3, 4])
print("Original array", org_val)

float_arr = org_val.astype(float)
print("Array converted to float type:", float_arr)

Original array [1 2 3 4]
Array converted to float type: [1. 2. 3. 4.]


In [9]:
#6. Celsius to Fahrenheit Conversion. Write a NumPy program to convert Centigrade degrees into Fahrenheit degrees. Centigrade values are stored in a NumPy array.
import numpy as np

centigrade = np.array([0, 12, 45.21, 34, 99.91])
fahrenheit = centigrade * 9/5 + 32

print(f"Celsius temperatures: {centigrade}")
print(f"Fahrenheit temperatures: {fahrenheit}")

Celsius temperatures: [ 0.   12.   45.21 34.   99.91]
Fahrenheit temperatures: [ 32.     53.6   113.378  93.2   211.838]


In [10]:
#7. Append Values to Array (Do self-study). Write a NumPy program to append values to the end of an array.
import numpy as np

org_vals = np.array([10, 20, 30])
print("Original array:", org_vals)

values_to_append = [40, 50, 60, 70, 80, 90]

new_arr = np.append(org_vals, values_to_append)
print("After append values to the end of the array:", new_arr)

Original array: [10 20 30]
After append values to the end of the array: [10 20 30 40 50 60 70 80 90]


In [14]:
#8. Array Statistical Functions (Do self-study). Create a random NumPy array of 10 elements and calculate the mean, median, and standard deviation of the array.
import numpy as np

array_values = np.random.rand(10)
print("Random array:", array_values)

mean_value = np.mean(array_values)
print("Mean:", mean_value)

median_value = np.median(array_values)
print("Median:", median_value)

std_value = np.std(array_values)
print("Standard Deviation:", std_value)

Random array: [0.6791313  0.00690889 0.07034796 0.78215267 0.57568724 0.31320172
 0.02483252 0.58181597 0.54976011 0.7348745 ]
Mean: 0.4318712894207441
Median: 0.5627236773869574
Standard Deviation: 0.28701304997975163


In [16]:
#9. Find min and max. Create a 10x10 array with random values and find the minimum and maximum values.
import numpy as np

arr_val = np.random.rand(10,10)
print("10x10 Random Array:\n", array_values)

min_value = np.min(array_values)
print("Minimum value:", min_value)

max_value = np.max(array_values)
print("Maximum value:", max_value)

10x10 Random Array:
 [0.6791313  0.00690889 0.07034796 0.78215267 0.57568724 0.31320172
 0.02483252 0.58181597 0.54976011 0.7348745 ]
Minimum value: 0.006908891881679091
Maximum value: 0.7821526741057966


In [18]:
#10. Create a 3x3x3 array with random values.
import numpy as np

arr_val = np.random.rand(3,3,3)
print("3x3x3 Random Array:\n", arr_val)

3x3x3 Random Array:
 [[[0.12539968 0.9281649  0.64389068]
  [0.05553609 0.66766865 0.59633373]
  [0.9716484  0.66986347 0.52352172]]

 [[0.65804472 0.94982121 0.14812442]
  [0.81728581 0.79764236 0.10338198]
  [0.01818942 0.01576175 0.10065609]]

 [[0.22432136 0.0476199  0.06597328]
  [0.16699138 0.70566603 0.18439335]
  [0.59412874 0.04735309 0.27664099]]]
